### ISSUE TITLE
Slide down charging information

### ISSUE THREAD

**Issue by Grant2k** [ArrowOS/android_frameworks_base#1]
If you turn on-off-on-off charging, then slide down charging information on lock screen 

![screenshot_20181028-113621](https://user-images.githubusercontent.com/29144739/47614273-e6b6d180-daa5-11e8-9a22-96446ce7e66f.png)
![screenshot_20181028-113610](https://user-images.githubusercontent.com/29144739/47614274-e6b6d180-daa5-11e8-83f1-7de17186166d.png)
![screenshot_20181028-115209](https://user-images.githubusercontent.com/29144739/47614415-5037df80-daa8-11e8-9150-0d273e662dcf.png)
![screenshot_20181028-115146](https://user-images.githubusercontent.com/29144739/47614434-85dcc880-daa8-11e8-8bf3-dafa5dc0ab2f.png)
![screenshot_20181028-115133](https://user-images.githubusercontent.com/29144739/47614437-8ecd9a00-daa8-11e8-9f6a-bbf42cf53c50.png)

**Comment by Bauuuuu** [comment]
this is fixed now. please wait for next update.
